package lt.neskelbiu.java.main.poster;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum City {
	VILNIUS("Vilnius"),
	Kaunas("Kaunas"),
	Klaipeda("Klaipėda"),
	Siauliai("Šiauliai"),
	Panevezys("Panevežys"),
	Alytus("Alytus"),
	Marijampole("Marijampolė"),
	Mažeikiai("Mažeikiai"),
	Jonava("Jonava"),
	Utena("Utena"),
	Neringa("Neringa"),
	Pagegiai("Pagėgiai"),
	Palanga("Palanga"),
	Kalvarija("Kalvarija"),
	Rietavas("Rietavas"),
	Birstonas("Birštonas"),
	Druskininkai("Druskininkai"),
	KazluRuda("KazlųRūda"),
	Elektrenai("Elektrėnai"),
	Visaginas("Visaginas"),
	AkmenesRajonas("Akmenės Rajonas"),
	AlytausRajonas("Alytaus Rajonas"),
	AnyksciuRajonas("Anykščių Rajonas"),
	BirzuRajonas("Biržų Rajonas"),
	IgnalinosRajonas("Ignalinos Rajonas"),
	JonavosRajonas("Jonavos Rajonas"),
	JoniskioRajonas("Joniškio Rajonas"),
	JurbarkoRajonas("Jurbarko Rajonas"),
	KaisiadoriuRajonas("Kaišiadorių Rajonas"),
	KaunoRajonas("Kauno Rajonas"),
	KedainiuRajonas("Kėdainių Rajonas"),
	KelmesRajonas("Kelmės Rajonas"),
	KlaipedosRajonas("Klaipėdos Rajonas"),
	KretingosRajonas("Kretingos Rajonas"),
	KupiskioRajonas("Kupiškio Rajonas"),
	LazdijuRajonas("Lazdijų Rajonas"),
	PakruojoRajonas("Pakruojo Rajonas"),
	MazeikiuRajonas("Mažeikių Rajonas"),
	MoletuRajonas("Molėtų Rajonas"),
	PanevezioRajonas("Panevėžio Rajonas"),
	PasvalioRajonas("Pasvalio Rajonas"),
	PlungesRajonas("Plungės Rajonas"),
	PrienuRajonas("Prienų Rajonas"),
	RadviliskioRajonas("Radviliškio Rajonas"),
	RaseiniuRajonas("Raseinių Rajonas"),
	RokiskioRajonas("Rokiškio Rajonas"),
	SkuodoRajonas("Skuodo Rajonas"),
	SakiuRajonas("Šakių Rajonas"),
	SalcininkuRajonas("Šalčininkų Rajonas"),
	SiauliuRajonas("Šiaulių Rajonas"),
	SilaleeRajonas("Šilalės Rajonas"),
	SilutesRajonas("Šilutės Rajonas"),
	SirvintuRajonas("Širvintų Rajonas"),
	SvenxioniuRajonas("Švenčionių Rajonas"),
	TauragesRajonas("Tauragės Rajonas"),
	TelsiuRajonas("Telšių Rajonas"),
	TrakuRajonas("Trakų Rajonas"),
	UkmergesRajonas("Ukmergės Rajonas"),
	UtenosRajonas("Utenos Rajonas"),
	VarenosRajonas("Varėnos Rajonas"),
	VilkaviskioRajonas("Vilkaviškio Rajonas"),
	VilniausRajonas("Vilniaus Rajonas"),
	ZarasuRajonas("Zarasų Rajonas"),
	Kita("Kita");

	@Getter
	private final String name;
}
