package lt.neskelbiu.java.main.poster;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum City {
	VILNIUS("Vilnius"),
	KAUNAS("Kaunas"),
	KLAIPEDA("Klaipėda"),
	SIAULIAI("Šiauliai"),
	PANEVEZYS("Panevežys"),
	ALYTUS("Alytus"),
	MARIJAMPOLE("Marijampolė"),
	MAZEIKIAI("Mažeikiai"),
	JONAVA("Jonava"),
	UTENA("Utena"),
	NERINGA("Neringa"),
	PAGEGIAI("Pagėgiai"),
	PALANGA("Palanga"),
	KALVARIJA("Kalvarija"),
	RIETAVAS("Rietavas"),
	BIRSTONAS("Birštonas"),
	DRUSKININKAI("Druskininkai"),
	KAZLURUDA("KazlųRūda"),
	ELEKTRENAI("Elektrėnai"),
	VISAGINAS("Visaginas"),
	AKMENES_RAJONAS("Akmenės Rajonas"),
	ALYTAUS_RAJONAS("Alytaus Rajonas"),
	ANYKSCIU_RAJONAS("Anykščių Rajonas"),
	BIRZU_RAJONAS("Biržų Rajonas"),
	IGNALINOS_RAJONAS("Ignalinos Rajonas"),
	JONAVOS_RAJONAS("Jonavos Rajonas"),
	JONISKIO_RAJONAS("Joniškio Rajonas"),
	JURBARKO_RAJONAS("Jurbarko Rajonas"),
	KAISIADO_RIURAJONAS("Kaišiadorių Rajonas"),
	KAUNO_RAJONAS("Kauno Rajonas"),
	KEDAINIU_RAJONAS("Kėdainių Rajonas"),
	KELMES_RAJONAS("Kelmės Rajonas"),
	KLAIPEDOS_RAJONAS("Klaipėdos Rajonas"),
	KRETINGOS_RAJONAS("Kretingos Rajonas"),
	KUPISKIO_RAJONAS("Kupiškio Rajonas"),
	LAZDIJU_RAJONAS("Lazdijų Rajonas"),
	PAKRUOJO_RAJONAS("Pakruojo Rajonas"),
	MAZEIKIU_RAJONAS("Mažeikių Rajonas"),
	MOLETU_RAJONAS("Molėtų Rajonas"),
	PANEVEZIO_RAJONAS("Panevėžio Rajonas"),
	PASVALIO_RAJONAS("Pasvalio Rajonas"),
	PLUNGES_RAJONAS("Plungės Rajonas"),
	PRIENU_RAJONAS("Prienų Rajonas"),
	RADVILISKIO_RAJONAS("Radviliškio Rajonas"),
	RASEINIU_RAJONAS("Raseinių Rajonas"),
	ROKISKIO_RAJONAS("Rokiškio Rajonas"),
	SKUODO_RAJONAS("Skuodo Rajonas"),
	SAKIU_RAJONAS("Šakių Rajonas"),
	SALCININKU_RAJONAS("Šalčininkų Rajonas"),
	SIAULIU_RAJONAS("Šiaulių Rajonas"),
	SILALES_RAJONAS("Šilalės Rajonas"),
	SILUTES_RAJONAS("Šilutės Rajonas"),
	SIRVINTU_RAJONAS("Širvintų Rajonas"),
	SVENCIONIU_RAJONAS("Švenčionių Rajonas"),
	TAURAGES_RAJONAS("Tauragės Rajonas"),
	TELSIU_RAJONAS("Telšių Rajonas"),
	TRAKU_RAJONAS("Trakų Rajonas"),
	UKMERGES_RAJONAS("Ukmergės Rajonas"),
	UTENOS_RAJONAS("Utenos Rajonas"),
	VARENOS_RAJONAS("Varėnos Rajonas"),
	VILKAVISKIO_RAJONAS("Vilkaviškio Rajonas"),
	VILNIAUS_RAJONAS("Vilniaus Rajonas"),
	ZARASU_RAJONAS("Zarasų Rajonas"),
	KITA("Kita");

	@Getter
	private final String name;
}
